# Generated by Django 4.2.11 on 2025-02-10 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crud',
            name='status',
        ),
    ]
